[package]
name = "frontend"
version = "0.2.0"
edition = "2024"
build = "build.rs"

[dependencies]
emulator = { path = "../emulator" }
slint = "1.14.1"
lucide-icons = "0.562.0"

[build-dependencies]
lucide-slint = "0.1.4"
slint-build = "1.14.1"
